# Generated by Django 4.1.2 on 2023-08-07 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobilephoneapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='description',
        ),
    ]
