# Generated by Django 4.1.2 on 2023-08-07 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobilephoneapp', '0003_banner_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='manufacture',
        ),
        migrations.DeleteModel(
            name='Manufacture',
        ),
    ]
