# Generated by Django 4.1.2 on 2023-08-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilephoneapp', '0004_remove_product_manufacture_delete_manufacture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(max_length=10),
        ),
    ]
