# Generated by Django 4.1.2 on 2023-08-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilephoneapp', '0006_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=13),
        ),
    ]
