# Generated by Django 4.1.2 on 2023-08-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilephoneapp', '0007_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='product',
            name='storage',
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(related_name='colors', to='mobilephoneapp.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='ram',
            field=models.ManyToManyField(related_name='rams', to='mobilephoneapp.ram'),
        ),
        migrations.AddField(
            model_name='product',
            name='storage',
            field=models.ManyToManyField(related_name='storages', to='mobilephoneapp.storage'),
        ),
    ]
