# Generated by Django 4.1.2 on 2023-08-07 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobilephoneapp', '0009_orderdetail_active_orderdetail_created_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderdetail',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='product',
        ),
    ]
